### ISSUE TITLE
Recipe details

### ISSUE THREAD

**Issue by soners** [soners/Recipe-Management-Android#4]
Request: As a user, I want to add my recipe details as text  and also add some photos of the ingredients, the cooking steps, and the final cooked food so that the recipes are more understandable and easier to follow.

Prerequisities:
Processing Recipes ( #3 ) 

Accept Conditions:
- [x] Adding details to recipes ( #11 )
- [x] Adding photos to recipes ( #12 )
- [x] Adding cooking steps to recipes ( #13 )
